version: 2
jobs:
  build:
    working_directory: ~/lukecollier.dev
    docker:
      - image: circleci/node:9.9.0-stretch
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install npm wee
          command: npm install
  deploy:
    working_directory: ~/lukecollier.dev
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Sync to google
          command: | 
                echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
                gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
                gsutil -m rsync -r public gs://www.lukecollier.dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
