version: 2
jobs:
  build-html:
    working_directory: ~/lukecollier.dev
    docker:
      - image: j1mc/docker-zola:0.8.0
    steps:
      - checkout
      - run:
          name: Build html
          command: 'sudo zola build'
      - store_artifacts:
          path: ./public
          destination: artifact-file
  build-styles:
    working_directory: ~/lukecollier.dev
    docker:
      - image: circleci/node:11.4.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run build:cd 
          command: npm run build:cd
      - store_artifacts:
          path: ./public
          destination: artifact-file
  deploy:
    working_directory: ~/lukecollier.dev
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Sync to google
          command: | 
                # echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
                # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
                # gsutil -m rsync -r public gs://www.lukecollier.dev

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
