version: 2
jobs:
  build-html:
    working_directory: ~/lukecollier.dev
    docker:
      - image: collierl/zola-alpine:0.0.5
    steps:
      - checkout
      - run:
          name: Build html
          command: 'zola build'
			- persist_to_workspace:
          root: /tmp
          paths:
            - public
      - store_artifacts:
          path: ./public
          destination: html
  build:
    working_directory: ~/lukecollier.dev
    docker:
      - image: circleci/node:11.4.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run build:cd 
          command: npm run build:cd
			- persist_to_workspace:
          root: /tmp
          paths:
            - public
      - store_artifacts:
          path: ./public
          destination: css
  deploy:
    working_directory: ~/lukecollier.dev
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Sync to google
          command: | 
                echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
                gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
                gsutil -m rsync -r /tmp/public gs://www.lukecollier.dev

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-html
      - build
      - deploy:
          requires:
            - build-html
            - build
          filters:
            branches:
              only: master
